table CLOUD_QUERY_HISTORY
	lineageTag: a56c8ac2-92d8-46e7-b731-00f46d81e2f9

	measure 'Total Warehouse' = DISTINCTCOUNTNOBLANK(CLOUD_QUERY_HISTORY[WAREHOUSE_NAME])
		formatString: 0
		lineageTag: 1b15ae6c-432b-4ba8-81bf-62dd2938c877

		changedProperty = IsHidden

	measure 'Total Database' = DISTINCTCOUNTNOBLANK(CLOUD_QUERY_HISTORY[DATABASE_NAME])
		formatString: 0
		lineageTag: 3dbb97b7-9520-4f01-90dd-c9da27e752c1

		changedProperty = IsHidden

	measure 'Total Queries' = COUNTA(CLOUD_QUERY_HISTORY[QUERY_ID])
		formatString: 0
		lineageTag: 002ec6e4-7ddb-4911-af1c-3b2fad450dc6

		changedProperty = IsHidden

	measure 'Total Users' = DISTINCTCOUNTNOBLANK(CLOUD_QUERY_HISTORY[USER_NAME])
		formatString: 0
		lineageTag: 3a9211ae-40cc-4aa8-b301-510156c55bf4

		changedProperty = IsHidden

	column QUERY_ID
		dataType: string
		lineageTag: 485b21e4-5eee-4956-9ec9-b908fbf173b9
		summarizeBy: none
		sourceColumn: QUERY_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column WAREHOUSE_NAME
		dataType: string
		lineageTag: fb337e96-48c8-489e-aad2-d08ad82a7cb4
		summarizeBy: none
		sourceColumn: WAREHOUSE_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ROLE_NAME
		dataType: string
		lineageTag: 52431551-d948-40b3-b127-d4b19f4099ac
		summarizeBy: none
		sourceColumn: ROLE_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column USER_NAME
		dataType: string
		lineageTag: 565b6f9d-0a08-40f0-8e6f-1353f2196013
		summarizeBy: none
		sourceColumn: USER_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SESSION_ID
		dataType: double
		lineageTag: 3585d25c-f211-4bfe-98b6-b9532b71d3e1
		summarizeBy: count
		sourceColumn: SESSION_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QUERY_TEXT
		dataType: string
		lineageTag: 81832482-5a01-4167-8f21-30ec0de223e7
		summarizeBy: none
		sourceColumn: QUERY_TEXT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column QUERY_TYPE
		dataType: string
		lineageTag: d9c4724a-8a08-4991-b361-803a3d672583
		summarizeBy: none
		sourceColumn: QUERY_TYPE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DATABASE_NAME
		dataType: string
		lineageTag: a6ac5af5-66b7-4d38-8262-b7e070f63d37
		summarizeBy: none
		sourceColumn: DATABASE_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SCHEMA_NAME
		dataType: string
		lineageTag: 0935025b-792f-441c-a2a6-858ce4871417
		summarizeBy: none
		sourceColumn: SCHEMA_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column QUERY_TAG
		dataType: string
		lineageTag: b6ffe458-609a-470a-bba9-2c0af5479c16
		summarizeBy: none
		sourceColumn: QUERY_TAG

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column START_TIME
		dataType: dateTime
		formatString: General Date
		lineageTag: 3c7addcc-5912-4f78-b645-6d82ebc68ce5
		summarizeBy: none
		sourceColumn: START_TIME

		variation Variation
			isDefault
			relationship: 9c264b9c-99eb-443d-ba1a-362434000e38
			defaultHierarchy: LocalDateTable_07ea5c35-32d6-410e-9cd0-11a76337ae04.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column END_TIME
		dataType: dateTime
		formatString: General Date
		lineageTag: bd393022-b132-499a-a124-0283261a92db
		summarizeBy: none
		sourceColumn: END_TIME

		variation Variation
			isDefault
			relationship: d335be0c-27cd-41f5-bc76-1548e939fbbd
			defaultHierarchy: LocalDateTable_acc46605-5bf3-4662-a0bd-95645822c3e2.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column STATUS
		dataType: string
		lineageTag: 28faf308-2afb-468d-b05a-78b518303ca7
		summarizeBy: none
		sourceColumn: STATUS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ERROR_CODE
		dataType: string
		lineageTag: 7e578190-2c92-4ef9-8724-14ddc11d8215
		summarizeBy: none
		sourceColumn: ERROR_CODE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ERROR_MESSAGE
		dataType: string
		lineageTag: 1dea6c78-2c82-4d15-b9f5-807306a7ea50
		summarizeBy: none
		sourceColumn: ERROR_MESSAGE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column INSERTED_BY
		dataType: string
		lineageTag: 73a7f6e7-5513-45e8-be93-b97542c870fc
		summarizeBy: none
		sourceColumn: INSERTED_BY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UPDATED_BY
		dataType: string
		lineageTag: 40e60beb-715c-41a3-a189-471cfde790cf
		summarizeBy: none
		sourceColumn: UPDATED_BY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column COMMENTS
		dataType: string
		lineageTag: 9607c755-e4f8-4dd8-b6aa-e23c3ed4adbf
		summarizeBy: none
		sourceColumn: COMMENTS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column INSERT_DATE
		dataType: dateTime
		formatString: General Date
		lineageTag: 8d7944bc-5d64-4255-9991-cd06ad0fb981
		summarizeBy: none
		sourceColumn: INSERT_DATE

		variation Variation
			isDefault
			relationship: 8ea6a96b-e268-4976-8443-71bbd177cba4
			defaultHierarchy: LocalDateTable_469be7e4-1667-433d-82cc-ad05d3a6d03f.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UPDATE_DATE
		dataType: dateTime
		formatString: General Date
		lineageTag: fd876cd0-74da-4198-be03-cb1df8ba5da2
		summarizeBy: none
		sourceColumn: UPDATE_DATE

		variation Variation
			isDefault
			relationship: 8129beb7-dbb6-4274-b9b0-00196c3c347d
			defaultHierarchy: LocalDateTable_b569a5d3-6e8d-41de-b56d-b503377cb4d5.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PLATFORM_NAME
		dataType: string
		lineageTag: 8185939f-1222-4bd7-85de-35f806c0efd1
		summarizeBy: none
		sourceColumn: PLATFORM_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Load Time'
		dataType: double
		lineageTag: 5a4cd802-e213-4bd7-9ed1-ae11a7d6c1e0
		summarizeBy: sum
		sourceColumn: Load Time

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CLOUD_QUERY_HISTORY_ROW_ID
		dataType: string
		lineageTag: 20d7eb01-0bdf-4b68-9def-1ba19b35825e
		summarizeBy: none
		sourceColumn: CLOUD_QUERY_HISTORY_ROW_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition CLOUD_QUERY_HISTORY = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("jujakkf-iq70734.snowflakecomputing.com","POWER_BI_WH"),
				    DM_DB_Database = Source{[Name="DM_DB",Kind="Database"]}[Data],
				    DATA_OBSERVABILITY_Schema = DM_DB_Database{[Name="DATA_OBSERVABILITY",Kind="Schema"]}[Data],
				    CLOUD_QUERY_HISTORY_Table = DATA_OBSERVABILITY_Schema{[Name="CLOUD_QUERY_HISTORY",Kind="Table"]}[Data],
				    #"Added Custom" = Table.AddColumn(CLOUD_QUERY_HISTORY_Table, "Load Time", each [END_TIME]-[START_TIME]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom",{{"Load Time", type duration}}),
				    #"Calculated Total Minutes" = Table.TransformColumns(#"Changed Type",{{"Load Time", Duration.TotalMinutes, type number}}),
				    #"Inserted Suffix" = Table.AddColumn(#"Calculated Total Minutes", "Suffix", each Text.From([Load Time], "en-IN") & " Mins", type text),
				    #"Removed Columns" = Table.RemoveColumns(#"Inserted Suffix",{"Suffix"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

