table JOB_RUN_LOG_SUMMARY
	lineageTag: 3a7d6634-dd2a-4e2f-a1e6-ab2ca6c4a52a

	measure 'Failed Jobs' = CALCULATE([Total Jobs],JOB_RUN_LOG_SUMMARY[JOB_STATUS]="Failed")
		formatString: 0
		lineageTag: b875c762-5ff6-4c3b-ac36-6a6465c616df

		changedProperty = IsHidden

	measure 'Success Jobs' = CALCULATE([Total Jobs],JOB_RUN_LOG_SUMMARY[JOB_STATUS]="SUCCESS")
		formatString: 0
		lineageTag: 4db33172-fa46-43f4-9667-c32ef593c169

		changedProperty = IsHidden

	measure SelectedSlicerValues = ```
			
			
			VAR total_second =
			CALCULATE(
			AVERAGEX(
			   
			    Filter(ALL(JOB_RUN_LOG_SUMMARY), (JOB_RUN_LOG_SUMMARY[PLATFORM_NAME]) IN VALUES(JOB_RUN_LOG_SUMMARY[PLATFORM_NAME]) || (JOB_RUN_LOG_SUMMARY[JOB_STATUS]) IN VALUES(JOB_RUN_LOG_SUMMARY[JOB_STATUS]) || (JOB_RUN_LOG_SUMMARY[JOB_START_TIME]) in VALUES(JOB_RUN_LOG_SUMMARY[JOB_START_TIME]) || (JOB_RUN_LOG_SUMMARY[JOB_END_TIME]) in VALUES(JOB_RUN_LOG_SUMMARY[JOB_END_TIME]) ),
			    DATEDIFF(JOB_RUN_LOG_SUMMARY[JOB_START_TIME],JOB_RUN_LOG_SUMMARY[JOB_END_TIME],SECOND)))
			VAR DAXDay   =  INT(total_second/(24*60*60))
			VAR DAXHours =  MOD(INT(total_second/(60*60)),24)
			VAR DAXMin   =  MOD(INT(total_second/60),60)
			VAR DAXSec   =  ROUND(MOD(total_second,60),0)
			
			RETURN DAXDay &" D "& DAXHours &" H "& DAXMin &" M "& DAXSec &" S"
			```
		lineageTag: 1119ba74-c334-4e18-8331-906669faf6ec

		changedProperty = IsHidden

	measure 'Total Jobs' = COUNTA(JOB_RUN_LOG_SUMMARY[JOB_ID])
		formatString: 0
		lineageTag: 25d6c53d-9a8d-48d5-8156-e539ceb01e64

		changedProperty = IsHidden

	measure 'Success Rate %' = divide([Success Jobs],[Total Jobs],0)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: c667685d-473d-4bea-a02e-6ff6479e96b6

		changedProperty = IsHidden

	measure 'Failure Rate %' = DIVIDE([Failed Jobs],[Total Jobs],0)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: cbcd8639-3548-481f-b591-1c1b0acc2c9f

		changedProperty = IsHidden

	column JOB_RUN_LOG_SUMMARY_ID
		dataType: string
		lineageTag: 27098433-5e1e-448b-8014-64f60a99ab30
		summarizeBy: none
		sourceColumn: JOB_RUN_LOG_SUMMARY_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PLATFORM_NAME
		dataType: string
		lineageTag: 6a449525-98a4-4b94-a773-e34e061a7ad3
		summarizeBy: none
		sourceColumn: PLATFORM_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column JOB_ID
		dataType: string
		lineageTag: 4b5de1f1-2beb-4581-ac04-be71dd9ff5ad
		summarizeBy: none
		sourceColumn: JOB_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column JOB_TASK_RUN_ID
		dataType: string
		lineageTag: 305bc480-55bd-4f60-a8d3-445eab612045
		summarizeBy: none
		sourceColumn: JOB_TASK_RUN_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column JOB_NAME
		dataType: string
		lineageTag: a4bf1f36-ac2e-4f9a-9fc3-9af83339b67f
		summarizeBy: none
		sourceColumn: JOB_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column JOB_STATUS
		dataType: string
		lineageTag: 6abf9da9-5765-43a4-b93b-ce0bfbca0c4b
		summarizeBy: none
		sourceColumn: JOB_STATUS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column JOB_START_TIME
		dataType: dateTime
		formatString: General Date
		lineageTag: b5d2722a-ca5f-4f3f-8b6b-68f0efb7ba4e
		summarizeBy: none
		sourceColumn: JOB_START_TIME

		variation Variation
			isDefault
			relationship: 24926eae-8eb9-41c5-9b6a-8d336d5c262d
			defaultHierarchy: LocalDateTable_6864e3e3-b162-4fe6-9e72-b57eec523d06.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column JOB_END_TIME
		dataType: dateTime
		formatString: General Date
		lineageTag: d73e89f8-2430-401c-938c-4573c3454ab9
		summarizeBy: none
		sourceColumn: JOB_END_TIME

		variation Variation
			isDefault
			relationship: d30ddae2-5f73-41e3-812e-a1d4650f6dbc
			defaultHierarchy: LocalDateTable_c9167e12-0468-4747-85da-d9bffe92a70a.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SOURCE_RECORD_COUNT
		dataType: int64
		formatString: 0
		lineageTag: 2dd635f3-5e9b-4c4a-9874-8ec08e17febb
		summarizeBy: sum
		sourceColumn: SOURCE_RECORD_COUNT

		changedProperty = DataType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PROCESSED_RECORD_COUNT
		dataType: double
		lineageTag: fabeded0-ec5c-416a-aa42-2ab2089aa6c4
		summarizeBy: sum
		sourceColumn: PROCESSED_RECORD_COUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ERROR_RECORD_COUNT
		dataType: double
		lineageTag: 09d7d5e8-76e5-48e2-946a-d2893ae78812
		summarizeBy: sum
		sourceColumn: ERROR_RECORD_COUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ERROR_MESSAGE
		dataType: string
		lineageTag: a68e1083-9d4b-49c1-9476-f911226b5fed
		summarizeBy: none
		sourceColumn: ERROR_MESSAGE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column JOB_NODE_NAME
		dataType: string
		lineageTag: a8f41e1d-75e2-48c0-b596-50da255fea8a
		summarizeBy: none
		sourceColumn: JOB_NODE_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column INSERTED_BY
		dataType: string
		lineageTag: e1dad972-47a7-4826-8703-63dc8a765b1e
		summarizeBy: none
		sourceColumn: INSERTED_BY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UPDATED_BY
		dataType: string
		lineageTag: 29da42ee-a665-42a4-a5e4-6bdea8a7f2a9
		summarizeBy: none
		sourceColumn: UPDATED_BY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column COMMENTS
		dataType: string
		lineageTag: 237f0d22-80b6-427a-9a12-36ead82af93e
		summarizeBy: none
		sourceColumn: COMMENTS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column INSERT_DATE
		dataType: dateTime
		formatString: General Date
		lineageTag: e7fb06ef-2706-4f55-8db1-33f2b754618b
		summarizeBy: none
		sourceColumn: INSERT_DATE

		variation Variation
			isDefault
			relationship: f8a4ee3d-a81c-49c2-b257-17efc3fa019b
			defaultHierarchy: LocalDateTable_c91c785e-d352-49ad-b925-be58ad56349c.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UPDATE_DATE
		dataType: dateTime
		formatString: General Date
		lineageTag: 2dcd1f88-ab03-4df5-96f9-6db528081d3f
		summarizeBy: none
		sourceColumn: UPDATE_DATE

		variation Variation
			isDefault
			relationship: dfa9f96b-6a90-4b7f-bc56-ef425142b8e1
			defaultHierarchy: LocalDateTable_f28c47e2-e504-4847-b82b-7fb276a78a5c.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Load Time' = DATEDIFF(JOB_RUN_LOG_SUMMARY[JOB_START_TIME],JOB_RUN_LOG_SUMMARY[JOB_END_TIME],SECOND)/60/60/24
		lineageTag: 5e867b78-9612-4ed9-bedf-bffe19c55da7
		summarizeBy: sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Days Bucket'
		dataType: string
		lineageTag: 95b04421-3a26-4e82-88bc-baeafc5d909e
		summarizeBy: none
		sourceColumn: Days Bucket

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Load Time in Secs'
		dataType: double
		lineageTag: 2b768b85-bca5-48fb-8402-7f3b648437b4
		summarizeBy: sum
		sourceColumn: Load Time in Secs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition JOB_RUN_LOG_SUMMARY = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("jujakkf-iq70734.snowflakecomputing.com","POWER_BI_WH"),
				    DM_DB_Database = Source{[Name="DM_DB",Kind="Database"]}[Data],
				    DATA_OBSERVABILITY_Schema = DM_DB_Database{[Name="DATA_OBSERVABILITY",Kind="Schema"]}[Data],
				    JOB_RUN_LOG_SUMMARY_Table = DATA_OBSERVABILITY_Schema{[Name="JOB_RUN_LOG_SUMMARY",Kind="Table"]}[Data],
				    #"Added Custom" = Table.AddColumn(JOB_RUN_LOG_SUMMARY_Table, "Load Time", each Duration.ToText([JOB_START_TIME]-[JOB_END_TIME])),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Custom",{{"Load Time", "Load Time CC"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"Load Time CC"}),
				    #"Added Custom1" = Table.AddColumn(#"Removed Columns", "Load DateTime", each Duration.ToText([JOB_START_TIME]-[JOB_END_TIME])),
				    #"Sorted Rows" = Table.Sort(#"Added Custom1",{{"Load DateTime", Order.Descending}}),
				    #"Added Custom4" = Table.AddColumn(#"Sorted Rows", "Load Time in Secs", each ([JOB_END_TIME]-[JOB_START_TIME])),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom4",{{"Load Time in Secs", type duration}}),
				    #"Calculated Total Seconds" = Table.TransformColumns(#"Changed Type",{{"Load Time in Secs", Duration.TotalSeconds, type number}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Calculated Total Seconds", "Days Bucket", each if [Load Time in Secs] >= 60 then "60 + Secs" else if [Load Time in Secs] >= 50 then "50 -59 Secs" else if [Load Time in Secs] >= 40 then "40 - 49 Secs" else if [Load Time in Secs] >= 30 then "30 - 39 Secs" else if [Load Time in Secs] >= 20 then "20 - 29 Secs" else if [Load Time in Secs] >= 10 then "10 -19 Secs" else if [Load Time in Secs] >= 0 then "0 - 9 Secs" else "< 0 secs"),
				    #"Removed Columns1" = Table.RemoveColumns(#"Added Conditional Column",{"Load DateTime"})
				in
				    #"Removed Columns1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

