table VW_DQ_RESULT_SUMMARY
	lineageTag: cb1287c2-6f45-41f2-90c6-75e5d4853218

	measure Accuracy = CALCULATE(sum(VW_DQ_RESULT_SUMMARY[PASS_RECORD_COUNT]),VW_DQ_RESULT_SUMMARY[RULE_CATEGORY]="Accuracy")
		lineageTag: b097ed90-0b99-4e0e-80fc-111eef6c8a54

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Accuracy Rate' = CALCULATE(sum(VW_DQ_RESULT_SUMMARY[SOURCE_RECORD_COUNT]),VW_DQ_RESULT_SUMMARY[RULE_CATEGORY]="Accuracy")
		lineageTag: c7d13e81-d29a-4e24-8639-5e523ce12550

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Accuracy Rate %' = DIVIDE([Accuracy],[Total Accuracy Rate],0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: ef4ba1a4-472a-44e2-a13a-0dd1051410e8

		changedProperty = IsHidden

	measure Uniqueness = CALCULATE(sum(VW_DQ_RESULT_SUMMARY[PASS_RECORD_COUNT]),VW_DQ_RESULT_SUMMARY[RULE_CATEGORY]="Uniqueness")
		lineageTag: 9bab1577-7fd8-48d0-99a9-96e1d08fa27f

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Completeness = CALCULATE(sum(VW_DQ_RESULT_SUMMARY[PASS_RECORD_COUNT]),VW_DQ_RESULT_SUMMARY[RULE_CATEGORY]="Completeness")
		lineageTag: ba9f2bce-a0ba-4eb2-9c16-63b897c484eb

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Integrity = CALCULATE(sum(VW_DQ_RESULT_SUMMARY[PASS_RECORD_COUNT]),VW_DQ_RESULT_SUMMARY[RULE_CATEGORY]="Integrity")
		lineageTag: 90b4af7a-9c39-450b-943e-f28fe00d625c

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Uniqueness Rate' = CALCULATE(sum(VW_DQ_RESULT_SUMMARY[SOURCE_RECORD_COUNT]),VW_DQ_RESULT_SUMMARY[RULE_CATEGORY]="Uniqueness")
		lineageTag: 6a7d18f2-2edc-4d0b-a052-8b620c012ca6

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Completeness Rate' = CALCULATE(sum(VW_DQ_RESULT_SUMMARY[SOURCE_RECORD_COUNT]),VW_DQ_RESULT_SUMMARY[RULE_CATEGORY]="Completeness")
		formatString: 0
		lineageTag: 114e754b-ed07-4584-bb3f-a5d2d5e72b1a

		changedProperty = IsHidden

	measure 'Total Integrity Rate' = CALCULATE(sum(VW_DQ_RESULT_SUMMARY[SOURCE_RECORD_COUNT]),VW_DQ_RESULT_SUMMARY[RULE_CATEGORY]="Integrity")
		lineageTag: 74cafe39-70c4-4ff1-a11a-1468ec00c98b

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Uniqueness Rate %' = DIVIDE([Uniqueness],[Total Uniqueness Rate],0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f6c13234-3962-44cd-a8c6-d1e299414764

		changedProperty = IsHidden

	measure 'Completeness Rate %' = DIVIDE([Completeness],[Total Completeness Rate],0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 71d4b718-bcd0-40f3-913f-ec47cbf97f88

		changedProperty = IsHidden

	measure 'Integrity Rate %' = DIVIDE([Integrity],[Total Integrity Rate],0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c985ac41-ae0f-4f6f-a7dd-b680ddd7fba5

		changedProperty = IsHidden

	measure 'DQ Target' = 1
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 3ede0d36-3336-45d9-8fa6-49f8b0b8da08

		changedProperty = IsHidden

	measure 'Uniqueness vs Target' =
			
			var uniquenesstarget = [DQ Target] - [Uniqueness Rate %]
			RETURN
			if (uniquenesstarget>=0,uniquenesstarget,0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e9ff1b6d-cd8d-474e-90aa-cb33a7e44dc9

		changedProperty = IsHidden

	measure 'Uniqueness pie' = ([Uniqueness Rate %]+[Uniqueness vs Target])*(1/3)
		lineageTag: 31ae2309-e734-435a-b127-1dccb1f8bb81

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Integrity vs Target' =
			
			var integritytarget = [DQ Target] - [Integrity Rate %]
			RETURN
			if (integritytarget>=0,integritytarget,0)
		lineageTag: 6d3655a9-4d9e-48c4-a837-56951c40e7bd

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Integrity pie' = ([Integrity Rate %]+[Integrity vs Target])*(1/3)
		lineageTag: 381f19de-8404-4b3d-b579-d90ad09103e4

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Completeness vs Target' =
			
			var completenesstarget = [DQ Target] - [Completeness Rate %]
			RETURN
			if (completenesstarget>=0,completenesstarget,0)
		lineageTag: d525f27c-e3ed-412a-a0b9-56f727058899

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Accuracy vs Target' =
			
			var Accuracytarget = [DQ Target] - [Accuracy Rate %]
			RETURN
			if (Accuracytarget>=0,Accuracytarget,0)
		lineageTag: 4974ee0c-7dd0-4f92-b07b-aadb225326e7

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Accuracy pie' = ([Accuracy Rate %]+[Accuracy vs Target])*(1/3)
		lineageTag: b37a20ff-915f-4815-a3c4-e53dd0b57263

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Completeness pie' = ([Completeness Rate %]+[Completeness vs Target])*(1/3)
		lineageTag: a6cdc3aa-5350-4e69-8de6-7cdf69b815c3

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Records Failed' = sum(VW_DQ_RESULT_SUMMARY[FAILED_RECORD_COUNT])
		lineageTag: b32e4ef4-69cb-4b37-be69-15593ffa29e8

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Records' = sum(VW_DQ_RESULT_SUMMARY[SOURCE_RECORD_COUNT])
		lineageTag: 2476d442-ea52-4d65-bf10-8e0505e4f3bf

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Records Pass' = sum(VW_DQ_RESULT_SUMMARY[PASS_RECORD_COUNT])
		lineageTag: 3aecaf69-9ced-4b8e-ab0a-c140d27ebb34

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DQ Score' = DIVIDE([Total Records Pass],[Total Records],0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: ccf53236-85bd-44ae-9de0-653f1f7a335c

		changedProperty = IsHidden

	measure 'Total Failed Tables' = CALCULATE(DISTINCTCOUNTNOBLANK(VW_DQ_RESULT_SUMMARY[Table Name]),VW_DQ_RESULT_SUMMARY[DQ_RESULT_STATUS] = "FAILED")
		formatString: 0
		lineageTag: b81342a4-d822-4d6c-a25f-04d66f1eac3a

		changedProperty = IsHidden

	measure 'RAG Amber' = 0.71
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 4b4ac29b-1151-4153-bf0b-f56921480f9f

		changedProperty = IsHidden

	measure 'DQ Target value' = 1
		formatString: 0
		lineageTag: 5019aee4-bee4-4126-9dcf-a1e9fc278345

		changedProperty = IsHidden

	measure 'RAG Green' = .95
		lineageTag: 31122b05-502b-4643-b05b-8f78ef7a64ba

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'RAG Red' = .70
		lineageTag: f7390f25-fa92-4cef-a6ff-3fe39721cf29

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Value = 100
		formatString: 0
		lineageTag: 3cd49395-ab21-4d33-9992-38bca94bb440

		changedProperty = IsHidden

	column DQ_RESULT_ID
		dataType: string
		lineageTag: fe7497b1-98c6-46b4-ae62-c1425f17fea2
		summarizeBy: none
		sourceColumn: DQ_RESULT_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PLATFORM_NAME
		dataType: string
		lineageTag: f4bfa448-aa2f-4331-9107-950bb2f20d5c
		summarizeBy: none
		sourceColumn: PLATFORM_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DQ_RUN_DATE
		dataType: dateTime
		formatString: General Date
		lineageTag: 70ab9d80-499d-41bb-b2de-623bdd442399
		summarizeBy: none
		sourceColumn: DQ_RUN_DATE

		variation Variation
			isDefault
			relationship: c9b55312-d212-4774-9e96-db299ed20d29
			defaultHierarchy: LocalDateTable_896f6908-153c-43bc-b701-2bd5e298e9c1.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column INPUT_FILE_NAME
		dataType: string
		lineageTag: a1f81b9b-ec78-4f53-8616-cd681b944be8
		summarizeBy: none
		sourceColumn: INPUT_FILE_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Database Name'
		dataType: string
		lineageTag: 58f94bae-65f7-4d46-bcd1-23e2fc6f91c2
		summarizeBy: none
		sourceColumn: Database Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SCHEMA_NAME
		dataType: string
		lineageTag: 3e2dc709-d053-4d5c-8dbf-4abb8bb97494
		summarizeBy: none
		sourceColumn: SCHEMA_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Table Name'
		dataType: string
		lineageTag: 7563d301-f0d6-4ae6-b23f-d14044f9471b
		summarizeBy: none
		sourceColumn: Table Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CRITICAL_DATA_ELEMENT_ID
		dataType: string
		lineageTag: 7be7d19d-8a15-46de-8b5b-ca02835746f6
		summarizeBy: none
		sourceColumn: CRITICAL_DATA_ELEMENT_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RULE_ID
		dataType: string
		lineageTag: 0be2ac33-c775-456e-a091-d44e65a958e1
		summarizeBy: none
		sourceColumn: RULE_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SOURCE_RECORD_COUNT
		dataType: double
		lineageTag: e106f591-3736-4636-a5f8-0a1b2b3430a9
		summarizeBy: sum
		sourceColumn: SOURCE_RECORD_COUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PASS_RECORD_COUNT
		dataType: double
		lineageTag: e6b2c3ec-cf6c-42a3-a613-d983e2eb4a36
		summarizeBy: sum
		sourceColumn: PASS_RECORD_COUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FAILED_RECORD_COUNT
		dataType: int64
		lineageTag: b4eb60c6-53f5-41a8-b261-7e4f1987ef2e
		summarizeBy: sum
		sourceColumn: FAILED_RECORD_COUNT

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DQ_RESULT_STATUS
		dataType: string
		lineageTag: 0e92ea61-f818-4d1d-87e1-553bec2a703e
		summarizeBy: none
		sourceColumn: DQ_RESULT_STATUS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column INSERTED_BY
		dataType: string
		lineageTag: e51681f3-a437-4a62-9fe5-8f383a1e296b
		summarizeBy: none
		sourceColumn: INSERTED_BY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UPDATED_BY
		dataType: string
		lineageTag: 61fe698e-d868-41c6-b2ad-4b26b0377a9b
		summarizeBy: none
		sourceColumn: UPDATED_BY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column COMMENTS
		dataType: string
		lineageTag: 025f0735-b75d-4f6a-9396-5203317fcd9e
		summarizeBy: none
		sourceColumn: COMMENTS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column INSERT_DATE
		dataType: dateTime
		formatString: General Date
		lineageTag: 1ae122aa-4dce-4c9f-bcea-276587ffcd92
		summarizeBy: none
		sourceColumn: INSERT_DATE

		variation Variation
			isDefault
			relationship: a968e4be-a3f0-4cec-82c3-5fe1aa12beb3
			defaultHierarchy: LocalDateTable_64360fcf-1253-45b9-a2c8-3616f100d902.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UPDATE_DATE
		dataType: dateTime
		formatString: General Date
		lineageTag: 5cf2df65-9643-4d54-9c0e-4e4d012b070a
		summarizeBy: none
		sourceColumn: UPDATE_DATE

		variation Variation
			isDefault
			relationship: e2340503-72a3-4d4e-8908-b108827df22c
			defaultHierarchy: LocalDateTable_275fd7c1-a1e7-482c-b7b7-10bea9526ab5.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RULE_NAME
		dataType: string
		lineageTag: 2510a722-f5eb-46a5-b153-45587a43c223
		summarizeBy: none
		sourceColumn: RULE_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RULE_TYPE
		dataType: string
		lineageTag: 2e776021-70df-4fa7-a3ba-b065ad084550
		summarizeBy: none
		sourceColumn: RULE_TYPE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RULE_CATEGORY
		dataType: string
		lineageTag: cd177bdb-1083-4d9b-9227-7b641ab6be9a
		summarizeBy: none
		sourceColumn: RULE_CATEGORY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition VW_DQ_RESULT_SUMMARY = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("jujakkf-iq70734.snowflakecomputing.com","POWER_BI_WH"),
				    DM_DB_Database = Source{[Name="DM_DB",Kind="Database"]}[Data],
				    DATA_OBSERVABILITY_Schema = DM_DB_Database{[Name="DATA_OBSERVABILITY",Kind="Schema"]}[Data],
				    VW_DQ_RESULT_SUMMARY_View = DATA_OBSERVABILITY_Schema{[Name="VW_DQ_RESULT_SUMMARY",Kind="View"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(VW_DQ_RESULT_SUMMARY_View,{{"DATABASE_NAME", "Database Name"}, {"TABLE_NAME", "Table Name"}})
				in
				    #"Renamed Columns"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

